version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  target-branch: dependency-updates
  ignore:
  - dependency-name: ch.acra:acra
    versions:
    - "> 4.6.2"
  - dependency-name: com.afollestad.material-dialogs:core
    versions:
    - ">= 2.a, < 3"
  - dependency-name: com.afollestad.material-dialogs:core
    versions:
    - ">= 3.a, < 4"
  - dependency-name: com.android.support:appcompat-v7
    versions:
    - "> 26.1.0"
  - dependency-name: com.android.support:customtabs
    versions:
    - "> 26.1.0"
  - dependency-name: com.android.support:design
    versions:
    - "> 26.1.0"
  - dependency-name: com.android.support:recyclerview-v7
    versions:
    - "> 26.1.0"
  - dependency-name: com.squareup.okhttp3:okhttp
    versions:
    - ">= 3.13.a, < 3.14"
  - dependency-name: com.squareup.okhttp3:okhttp
    versions:
    - ">= 3.14.a, < 3.15"
  - dependency-name: org.apache.commons:commons-compress
    versions:
    - "> 1.12"
  - dependency-name: com.github.triplet.play
    versions:
    - 3.2.0-agp4.2-2
    - 3.3.0-agp4.2
  - dependency-name: androidx.recyclerview:recyclerview
    versions:
    - 1.2.0
  - dependency-name: io.github.david-allison-1:anki-android-backend-testing
    versions:
    - 0.1.4
  - dependency-name: io.github.david-allison-1:anki-android-backend
    versions:
    - 0.1.4
  - dependency-name: androidx.fragment:fragment-testing
    versions:
    - 1.3.0
    - 1.3.1
  - dependency-name: com.squareup.okhttp3:okhttp
    versions:
    - 3.12.13
